Added Shutdown-Script

diff --git a/bin/team-shutdown b/bin/team-shutdown
--- a/bin/team-shutdown
+++ b/bin/team-shutdown
@@ -4,6 +4,6 @@
 require team
 
 for module in ssh docker serf bee swarm flanneld etcd interlock registry zookeeper dokku; do
-  echo "Clean up $module"
-  $TEAM $module clean 2>/dev/null || echo "$module shutdown failed"
+  echo -n "Shutdown $module ... "
+  $TEAM $module clean 2>/dev/null && echo "ok" || echo "failed"
 done
